/********************************************************************************
** Form generated from reading UI file 'hearthstone.ui'
**
** Created by: Qt User Interface Compiler version 6.1.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_HEARTHSTONE_H
#define UI_HEARTHSTONE_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_HearthstoneClass
{
public:
    QLabel *logo;
    QPushButton *start;
    QPushButton *done;
    QLabel *chooseInfo1;
    QLabel *chooseInfo0;
    QLabel *prompt0;
    QLabel *gameInfo1;
    QLabel *gameInfo3;
    QLabel *gameInfo0;
    QLabel *gameInfo2;
    QPushButton *finish;
    QLabel *prompt1;
    QLabel *cardView;
    QLabel *history;
    QPushButton *chooseBtn5;
    QPushButton *chooseBtn6;
    QPushButton *chooseBtn3;
    QPushButton *chooseBtn1;
    QPushButton *chooseBtn2;
    QPushButton *chooseBtn4;
    QPushButton *chooseBtn0;
    QPushButton *cardBtn2;
    QPushButton *cardBtn0;
    QPushButton *cardBtn1;
    QPushButton *cardBtn5;
    QPushButton *cardBtn3;
    QPushButton *cardBtn4;
    QPushButton *cardBtn6;
    QPushButton *cardBtn7;
    QPushButton *cardBtn8;
    QPushButton *cardBtn9;
    QPushButton *darkMinion0;
    QPushButton *darkMinion1;
    QPushButton *darkMinion2;
    QPushButton *darkMinion3;
    QPushButton *darkMinion4;
    QPushButton *darkMinion5;
    QPushButton *darkMinion6;
    QPushButton *lightMinion0;
    QPushButton *lightMinion1;
    QPushButton *lightMinion2;
    QPushButton *lightMinion3;
    QPushButton *lightMinion4;
    QPushButton *lightMinion5;
    QPushButton *lightMinion6;
    QPushButton *lightPlace0;
    QPushButton *lightPlace1;
    QPushButton *lightPlace2;
    QPushButton *lightPlace3;
    QPushButton *lightPlace4;
    QPushButton *lightPlace5;
    QPushButton *lightPlace6;
    QPushButton *lightPlace7;
    QPushButton *darkPlace1;
    QPushButton *darkPlace7;
    QPushButton *darkPlace2;
    QPushButton *darkPlace4;
    QPushButton *darkPlace5;
    QPushButton *darkPlace3;
    QPushButton *darkPlace0;
    QPushButton *darkPlace6;
    QPushButton *lightSkill;
    QPushButton *darkSkill;
    QLabel *lightMinionA0;
    QLabel *lightMinionA1;
    QLabel *lightMinionA2;
    QLabel *lightMinionA3;
    QLabel *lightMinionA4;
    QLabel *lightMinionA5;
    QLabel *lightMinionA6;
    QLabel *lightMinionH0;
    QLabel *lightMinionH1;
    QLabel *lightMinionH4;
    QLabel *lightMinionH2;
    QLabel *lightMinionH3;
    QLabel *lightMinionH5;
    QLabel *lightMinionH6;
    QLabel *darkMinionH3;
    QLabel *darkMinionA0;
    QLabel *darkMinionH2;
    QLabel *darkMinionA4;
    QLabel *darkMinionH0;
    QLabel *darkMinionA5;
    QLabel *darkMinionH4;
    QLabel *darkMinionA1;
    QLabel *darkMinionH1;
    QLabel *darkMinionA2;
    QLabel *darkMinionA3;
    QLabel *darkMinionH6;
    QLabel *darkMinionH5;
    QLabel *darkMinionA6;
    QLabel *darkMinionI6;
    QLabel *darkMinionI1;
    QLabel *darkMinionI5;
    QLabel *darkMinionI3;
    QLabel *darkMinionI2;
    QLabel *darkMinionI0;
    QLabel *darkMinionI4;
    QLabel *lightMinionI0;
    QLabel *lightMinionI1;
    QLabel *lightMinionI5;
    QLabel *lightMinionI6;
    QLabel *lightMinionI2;
    QLabel *lightMinionI3;
    QLabel *lightMinionI4;
    QLabel *lightHeroA;
    QLabel *lightHeroH;
    QLabel *darkHeroA;
    QLabel *darkHeroH;
    QLabel *lightWeaponA;
    QLabel *lightWeaponH;
    QLabel *darkWeaponA;
    QLabel *darkWeaponH;
    QLabel *darkSubFrame;
    QLabel *lightSubFrame;
    QPushButton *darkChoice0;
    QPushButton *darkChoice1;
    QPushButton *lightChoice1;
    QPushButton *lightChoice0;
    QLabel *prompt2;
    QPushButton *quit;
    QLabel *quitMessage;
    QLabel *mana0;
    QLabel *mana1;
    QLabel *mana2;
    QLabel *mana3;
    QLabel *mana4;
    QLabel *mana5;
    QLabel *mana6;
    QLabel *mana7;
    QLabel *mana8;
    QLabel *mana9;
    QPushButton *cancel;
    QLabel *lightWeapon;
    QLabel *darkWeapon;
    QPushButton *darkHero;
    QPushButton *lightHero;
    QLabel *darkHeroI;
    QLabel *lightHeroI;
    QPushButton *chooseBtn0r;
    QPushButton *chooseBtn4r;
    QPushButton *chooseBtn3r;
    QPushButton *chooseBtn1r;
    QPushButton *chooseBtn5r;
    QPushButton *chooseBtn6r;
    QPushButton *chooseBtn2r;
    QLabel *cardMana;
    QLabel *cardAttack;
    QLabel *cardHealth;
    QLabel *cardSkill;
    QPushButton *place;
    QLabel *lightWeaponI;
    QLabel *darkWeaponI;

    void setupUi(QWidget *HearthstoneClass)
    {
        if (HearthstoneClass->objectName().isEmpty())
            HearthstoneClass->setObjectName(QString::fromUtf8("HearthstoneClass"));
        HearthstoneClass->resize(1500, 900);
        HearthstoneClass->setMinimumSize(QSize(1500, 900));
        HearthstoneClass->setMaximumSize(QSize(1500, 900));
        logo = new QLabel(HearthstoneClass);
        logo->setObjectName(QString::fromUtf8("logo"));
        logo->setGeometry(QRect(150, 0, 1200, 600));
        logo->setPixmap(QPixmap(QString::fromUtf8("LOGO.png")));
        logo->setScaledContents(true);
        start = new QPushButton(HearthstoneClass);
        start->setObjectName(QString::fromUtf8("start"));
        start->setGeometry(QRect(700, 800, 100, 30));
        done = new QPushButton(HearthstoneClass);
        done->setObjectName(QString::fromUtf8("done"));
        done->setGeometry(QRect(1218, 265, 100, 30));
        chooseInfo1 = new QLabel(HearthstoneClass);
        chooseInfo1->setObjectName(QString::fromUtf8("chooseInfo1"));
        chooseInfo1->setGeometry(QRect(108, 460, 700, 60));
        QFont font;
        font.setPointSize(20);
        chooseInfo1->setFont(font);
        chooseInfo0 = new QLabel(HearthstoneClass);
        chooseInfo0->setObjectName(QString::fromUtf8("chooseInfo0"));
        chooseInfo0->setGeometry(QRect(108, 10, 700, 60));
        chooseInfo0->setFont(font);
        prompt0 = new QLabel(HearthstoneClass);
        prompt0->setObjectName(QString::fromUtf8("prompt0"));
        prompt0->setGeometry(QRect(950, 10, 500, 60));
        prompt0->setFont(font);
        prompt0->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gameInfo1 = new QLabel(HearthstoneClass);
        gameInfo1->setObjectName(QString::fromUtf8("gameInfo1"));
        gameInfo1->setGeometry(QRect(235, 690, 100, 30));
        gameInfo3 = new QLabel(HearthstoneClass);
        gameInfo3->setObjectName(QString::fromUtf8("gameInfo3"));
        gameInfo3->setGeometry(QRect(345, 690, 100, 30));
        gameInfo0 = new QLabel(HearthstoneClass);
        gameInfo0->setObjectName(QString::fromUtf8("gameInfo0"));
        gameInfo0->setGeometry(QRect(15, 690, 100, 30));
        gameInfo2 = new QLabel(HearthstoneClass);
        gameInfo2->setObjectName(QString::fromUtf8("gameInfo2"));
        gameInfo2->setGeometry(QRect(125, 690, 100, 30));
        finish = new QPushButton(HearthstoneClass);
        finish->setObjectName(QString::fromUtf8("finish"));
        finish->setGeometry(QRect(1375, 840, 100, 30));
        prompt1 = new QLabel(HearthstoneClass);
        prompt1->setObjectName(QString::fromUtf8("prompt1"));
        prompt1->setGeometry(QRect(600, 10, 300, 60));
        prompt1->setFont(font);
        prompt1->setAlignment(Qt::AlignCenter);
        cardView = new QLabel(HearthstoneClass);
        cardView->setObjectName(QString::fromUtf8("cardView"));
        cardView->setGeometry(QRect(15, 80, 240, 341));
        QFont font1;
        font1.setPointSize(18);
        cardView->setFont(font1);
        cardView->setFrameShape(QFrame::Box);
        cardView->setTextFormat(Qt::AutoText);
        cardView->setAlignment(Qt::AlignCenter);
        history = new QLabel(HearthstoneClass);
        history->setObjectName(QString::fromUtf8("history"));
        history->setGeometry(QRect(15, 435, 500, 250));
        QFont font2;
        font2.setPointSize(13);
        history->setFont(font2);
        history->setFrameShape(QFrame::Box);
        history->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        chooseBtn5 = new QPushButton(HearthstoneClass);
        chooseBtn5->setObjectName(QString::fromUtf8("chooseBtn5"));
        chooseBtn5->setGeometry(QRect(800, 540, 240, 341));
        chooseBtn5->setMinimumSize(QSize(240, 341));
        chooseBtn5->setMaximumSize(QSize(240, 341));
        chooseBtn6 = new QPushButton(HearthstoneClass);
        chooseBtn6->setObjectName(QString::fromUtf8("chooseBtn6"));
        chooseBtn6->setGeometry(QRect(1148, 540, 240, 341));
        chooseBtn6->setMinimumSize(QSize(240, 341));
        chooseBtn6->setMaximumSize(QSize(240, 341));
        chooseBtn3 = new QPushButton(HearthstoneClass);
        chooseBtn3->setObjectName(QString::fromUtf8("chooseBtn3"));
        chooseBtn3->setGeometry(QRect(108, 540, 240, 341));
        chooseBtn3->setMinimumSize(QSize(240, 341));
        chooseBtn3->setMaximumSize(QSize(240, 341));
        chooseBtn1 = new QPushButton(HearthstoneClass);
        chooseBtn1->setObjectName(QString::fromUtf8("chooseBtn1"));
        chooseBtn1->setGeometry(QRect(452, 90, 240, 341));
        chooseBtn1->setMinimumSize(QSize(240, 341));
        chooseBtn1->setMaximumSize(QSize(240, 341));
        chooseBtn2 = new QPushButton(HearthstoneClass);
        chooseBtn2->setObjectName(QString::fromUtf8("chooseBtn2"));
        chooseBtn2->setGeometry(QRect(800, 90, 240, 341));
        chooseBtn2->setMinimumSize(QSize(240, 341));
        chooseBtn2->setMaximumSize(QSize(240, 341));
        chooseBtn4 = new QPushButton(HearthstoneClass);
        chooseBtn4->setObjectName(QString::fromUtf8("chooseBtn4"));
        chooseBtn4->setGeometry(QRect(452, 540, 240, 341));
        chooseBtn4->setMinimumSize(QSize(240, 341));
        chooseBtn4->setMaximumSize(QSize(240, 341));
        chooseBtn0 = new QPushButton(HearthstoneClass);
        chooseBtn0->setObjectName(QString::fromUtf8("chooseBtn0"));
        chooseBtn0->setGeometry(QRect(108, 90, 240, 341));
        chooseBtn0->setMinimumSize(QSize(240, 341));
        chooseBtn0->setMaximumSize(QSize(240, 341));
        cardBtn2 = new QPushButton(HearthstoneClass);
        cardBtn2->setObjectName(QString::fromUtf8("cardBtn2"));
        cardBtn2->setGeometry(QRect(285, 720, 120, 171));
        cardBtn2->setMinimumSize(QSize(120, 171));
        cardBtn2->setMaximumSize(QSize(120, 171));
        cardBtn0 = new QPushButton(HearthstoneClass);
        cardBtn0->setObjectName(QString::fromUtf8("cardBtn0"));
        cardBtn0->setGeometry(QRect(15, 720, 120, 171));
        cardBtn0->setMinimumSize(QSize(120, 171));
        cardBtn0->setMaximumSize(QSize(120, 171));
        cardBtn1 = new QPushButton(HearthstoneClass);
        cardBtn1->setObjectName(QString::fromUtf8("cardBtn1"));
        cardBtn1->setGeometry(QRect(150, 720, 120, 171));
        cardBtn1->setMinimumSize(QSize(120, 171));
        cardBtn1->setMaximumSize(QSize(120, 171));
        cardBtn5 = new QPushButton(HearthstoneClass);
        cardBtn5->setObjectName(QString::fromUtf8("cardBtn5"));
        cardBtn5->setGeometry(QRect(690, 720, 120, 171));
        cardBtn5->setMinimumSize(QSize(120, 171));
        cardBtn5->setMaximumSize(QSize(120, 171));
        cardBtn3 = new QPushButton(HearthstoneClass);
        cardBtn3->setObjectName(QString::fromUtf8("cardBtn3"));
        cardBtn3->setGeometry(QRect(420, 720, 120, 171));
        cardBtn3->setMinimumSize(QSize(120, 171));
        cardBtn3->setMaximumSize(QSize(120, 171));
        cardBtn4 = new QPushButton(HearthstoneClass);
        cardBtn4->setObjectName(QString::fromUtf8("cardBtn4"));
        cardBtn4->setGeometry(QRect(555, 720, 120, 171));
        cardBtn4->setMinimumSize(QSize(120, 171));
        cardBtn4->setMaximumSize(QSize(120, 171));
        cardBtn6 = new QPushButton(HearthstoneClass);
        cardBtn6->setObjectName(QString::fromUtf8("cardBtn6"));
        cardBtn6->setGeometry(QRect(825, 720, 120, 171));
        cardBtn6->setMinimumSize(QSize(120, 171));
        cardBtn6->setMaximumSize(QSize(120, 171));
        cardBtn7 = new QPushButton(HearthstoneClass);
        cardBtn7->setObjectName(QString::fromUtf8("cardBtn7"));
        cardBtn7->setGeometry(QRect(960, 720, 120, 171));
        cardBtn7->setMinimumSize(QSize(120, 171));
        cardBtn7->setMaximumSize(QSize(120, 171));
        cardBtn8 = new QPushButton(HearthstoneClass);
        cardBtn8->setObjectName(QString::fromUtf8("cardBtn8"));
        cardBtn8->setGeometry(QRect(1095, 720, 120, 171));
        cardBtn8->setMinimumSize(QSize(120, 171));
        cardBtn8->setMaximumSize(QSize(120, 171));
        cardBtn9 = new QPushButton(HearthstoneClass);
        cardBtn9->setObjectName(QString::fromUtf8("cardBtn9"));
        cardBtn9->setGeometry(QRect(1230, 720, 120, 171));
        cardBtn9->setMinimumSize(QSize(120, 171));
        cardBtn9->setMaximumSize(QSize(120, 171));
        darkMinion0 = new QPushButton(HearthstoneClass);
        darkMinion0->setObjectName(QString::fromUtf8("darkMinion0"));
        darkMinion0->setGeometry(QRect(600, 270, 80, 80));
        darkMinion1 = new QPushButton(HearthstoneClass);
        darkMinion1->setObjectName(QString::fromUtf8("darkMinion1"));
        darkMinion1->setGeometry(QRect(720, 270, 80, 80));
        darkMinion2 = new QPushButton(HearthstoneClass);
        darkMinion2->setObjectName(QString::fromUtf8("darkMinion2"));
        darkMinion2->setGeometry(QRect(840, 270, 80, 80));
        darkMinion3 = new QPushButton(HearthstoneClass);
        darkMinion3->setObjectName(QString::fromUtf8("darkMinion3"));
        darkMinion3->setGeometry(QRect(960, 270, 80, 80));
        darkMinion4 = new QPushButton(HearthstoneClass);
        darkMinion4->setObjectName(QString::fromUtf8("darkMinion4"));
        darkMinion4->setGeometry(QRect(1080, 270, 80, 80));
        darkMinion5 = new QPushButton(HearthstoneClass);
        darkMinion5->setObjectName(QString::fromUtf8("darkMinion5"));
        darkMinion5->setGeometry(QRect(1200, 270, 80, 80));
        darkMinion6 = new QPushButton(HearthstoneClass);
        darkMinion6->setObjectName(QString::fromUtf8("darkMinion6"));
        darkMinion6->setGeometry(QRect(1320, 270, 80, 80));
        lightMinion0 = new QPushButton(HearthstoneClass);
        lightMinion0->setObjectName(QString::fromUtf8("lightMinion0"));
        lightMinion0->setGeometry(QRect(600, 390, 80, 80));
        lightMinion1 = new QPushButton(HearthstoneClass);
        lightMinion1->setObjectName(QString::fromUtf8("lightMinion1"));
        lightMinion1->setGeometry(QRect(720, 390, 80, 80));
        lightMinion2 = new QPushButton(HearthstoneClass);
        lightMinion2->setObjectName(QString::fromUtf8("lightMinion2"));
        lightMinion2->setGeometry(QRect(840, 390, 80, 80));
        lightMinion3 = new QPushButton(HearthstoneClass);
        lightMinion3->setObjectName(QString::fromUtf8("lightMinion3"));
        lightMinion3->setGeometry(QRect(960, 390, 80, 80));
        lightMinion4 = new QPushButton(HearthstoneClass);
        lightMinion4->setObjectName(QString::fromUtf8("lightMinion4"));
        lightMinion4->setGeometry(QRect(1080, 390, 80, 80));
        lightMinion5 = new QPushButton(HearthstoneClass);
        lightMinion5->setObjectName(QString::fromUtf8("lightMinion5"));
        lightMinion5->setGeometry(QRect(1200, 390, 80, 80));
        lightMinion6 = new QPushButton(HearthstoneClass);
        lightMinion6->setObjectName(QString::fromUtf8("lightMinion6"));
        lightMinion6->setGeometry(QRect(1320, 390, 80, 80));
        lightPlace0 = new QPushButton(HearthstoneClass);
        lightPlace0->setObjectName(QString::fromUtf8("lightPlace0"));
        lightPlace0->setGeometry(QRect(570, 390, 20, 80));
        lightPlace1 = new QPushButton(HearthstoneClass);
        lightPlace1->setObjectName(QString::fromUtf8("lightPlace1"));
        lightPlace1->setGeometry(QRect(690, 390, 20, 80));
        lightPlace2 = new QPushButton(HearthstoneClass);
        lightPlace2->setObjectName(QString::fromUtf8("lightPlace2"));
        lightPlace2->setGeometry(QRect(810, 390, 20, 80));
        lightPlace3 = new QPushButton(HearthstoneClass);
        lightPlace3->setObjectName(QString::fromUtf8("lightPlace3"));
        lightPlace3->setGeometry(QRect(930, 390, 20, 80));
        lightPlace4 = new QPushButton(HearthstoneClass);
        lightPlace4->setObjectName(QString::fromUtf8("lightPlace4"));
        lightPlace4->setGeometry(QRect(1050, 390, 20, 80));
        lightPlace5 = new QPushButton(HearthstoneClass);
        lightPlace5->setObjectName(QString::fromUtf8("lightPlace5"));
        lightPlace5->setGeometry(QRect(1170, 390, 20, 80));
        lightPlace6 = new QPushButton(HearthstoneClass);
        lightPlace6->setObjectName(QString::fromUtf8("lightPlace6"));
        lightPlace6->setGeometry(QRect(1290, 390, 20, 80));
        lightPlace7 = new QPushButton(HearthstoneClass);
        lightPlace7->setObjectName(QString::fromUtf8("lightPlace7"));
        lightPlace7->setGeometry(QRect(1410, 390, 20, 80));
        darkPlace1 = new QPushButton(HearthstoneClass);
        darkPlace1->setObjectName(QString::fromUtf8("darkPlace1"));
        darkPlace1->setGeometry(QRect(690, 270, 20, 80));
        darkPlace7 = new QPushButton(HearthstoneClass);
        darkPlace7->setObjectName(QString::fromUtf8("darkPlace7"));
        darkPlace7->setGeometry(QRect(1410, 270, 20, 80));
        darkPlace2 = new QPushButton(HearthstoneClass);
        darkPlace2->setObjectName(QString::fromUtf8("darkPlace2"));
        darkPlace2->setGeometry(QRect(810, 270, 20, 80));
        darkPlace4 = new QPushButton(HearthstoneClass);
        darkPlace4->setObjectName(QString::fromUtf8("darkPlace4"));
        darkPlace4->setGeometry(QRect(1050, 270, 20, 80));
        darkPlace5 = new QPushButton(HearthstoneClass);
        darkPlace5->setObjectName(QString::fromUtf8("darkPlace5"));
        darkPlace5->setGeometry(QRect(1170, 270, 20, 80));
        darkPlace3 = new QPushButton(HearthstoneClass);
        darkPlace3->setObjectName(QString::fromUtf8("darkPlace3"));
        darkPlace3->setGeometry(QRect(930, 270, 20, 80));
        darkPlace0 = new QPushButton(HearthstoneClass);
        darkPlace0->setObjectName(QString::fromUtf8("darkPlace0"));
        darkPlace0->setGeometry(QRect(570, 270, 20, 80));
        darkPlace6 = new QPushButton(HearthstoneClass);
        darkPlace6->setObjectName(QString::fromUtf8("darkPlace6"));
        darkPlace6->setGeometry(QRect(1290, 270, 20, 80));
        lightSkill = new QPushButton(HearthstoneClass);
        lightSkill->setObjectName(QString::fromUtf8("lightSkill"));
        lightSkill->setGeometry(QRect(1050, 550, 80, 80));
        darkSkill = new QPushButton(HearthstoneClass);
        darkSkill->setObjectName(QString::fromUtf8("darkSkill"));
        darkSkill->setGeometry(QRect(1050, 110, 80, 80));
        lightMinionA0 = new QLabel(HearthstoneClass);
        lightMinionA0->setObjectName(QString::fromUtf8("lightMinionA0"));
        lightMinionA0->setGeometry(QRect(600, 470, 40, 20));
        lightMinionA0->setAlignment(Qt::AlignCenter);
        lightMinionA1 = new QLabel(HearthstoneClass);
        lightMinionA1->setObjectName(QString::fromUtf8("lightMinionA1"));
        lightMinionA1->setGeometry(QRect(720, 470, 40, 20));
        lightMinionA1->setAlignment(Qt::AlignCenter);
        lightMinionA2 = new QLabel(HearthstoneClass);
        lightMinionA2->setObjectName(QString::fromUtf8("lightMinionA2"));
        lightMinionA2->setGeometry(QRect(840, 470, 40, 20));
        lightMinionA2->setAlignment(Qt::AlignCenter);
        lightMinionA3 = new QLabel(HearthstoneClass);
        lightMinionA3->setObjectName(QString::fromUtf8("lightMinionA3"));
        lightMinionA3->setGeometry(QRect(960, 470, 40, 20));
        lightMinionA3->setAlignment(Qt::AlignCenter);
        lightMinionA4 = new QLabel(HearthstoneClass);
        lightMinionA4->setObjectName(QString::fromUtf8("lightMinionA4"));
        lightMinionA4->setGeometry(QRect(1080, 470, 40, 20));
        lightMinionA4->setAlignment(Qt::AlignCenter);
        lightMinionA5 = new QLabel(HearthstoneClass);
        lightMinionA5->setObjectName(QString::fromUtf8("lightMinionA5"));
        lightMinionA5->setGeometry(QRect(1200, 470, 40, 20));
        lightMinionA5->setAlignment(Qt::AlignCenter);
        lightMinionA6 = new QLabel(HearthstoneClass);
        lightMinionA6->setObjectName(QString::fromUtf8("lightMinionA6"));
        lightMinionA6->setGeometry(QRect(1320, 470, 40, 20));
        lightMinionA6->setAlignment(Qt::AlignCenter);
        lightMinionH0 = new QLabel(HearthstoneClass);
        lightMinionH0->setObjectName(QString::fromUtf8("lightMinionH0"));
        lightMinionH0->setGeometry(QRect(640, 470, 40, 20));
        lightMinionH0->setAlignment(Qt::AlignCenter);
        lightMinionH1 = new QLabel(HearthstoneClass);
        lightMinionH1->setObjectName(QString::fromUtf8("lightMinionH1"));
        lightMinionH1->setGeometry(QRect(760, 470, 40, 20));
        lightMinionH1->setAlignment(Qt::AlignCenter);
        lightMinionH4 = new QLabel(HearthstoneClass);
        lightMinionH4->setObjectName(QString::fromUtf8("lightMinionH4"));
        lightMinionH4->setGeometry(QRect(1120, 470, 40, 20));
        lightMinionH4->setAlignment(Qt::AlignCenter);
        lightMinionH2 = new QLabel(HearthstoneClass);
        lightMinionH2->setObjectName(QString::fromUtf8("lightMinionH2"));
        lightMinionH2->setGeometry(QRect(880, 470, 40, 20));
        lightMinionH2->setAlignment(Qt::AlignCenter);
        lightMinionH3 = new QLabel(HearthstoneClass);
        lightMinionH3->setObjectName(QString::fromUtf8("lightMinionH3"));
        lightMinionH3->setGeometry(QRect(1000, 470, 40, 20));
        lightMinionH3->setAlignment(Qt::AlignCenter);
        lightMinionH5 = new QLabel(HearthstoneClass);
        lightMinionH5->setObjectName(QString::fromUtf8("lightMinionH5"));
        lightMinionH5->setGeometry(QRect(1240, 470, 40, 20));
        lightMinionH5->setAlignment(Qt::AlignCenter);
        lightMinionH6 = new QLabel(HearthstoneClass);
        lightMinionH6->setObjectName(QString::fromUtf8("lightMinionH6"));
        lightMinionH6->setGeometry(QRect(1360, 470, 40, 20));
        lightMinionH6->setAlignment(Qt::AlignCenter);
        darkMinionH3 = new QLabel(HearthstoneClass);
        darkMinionH3->setObjectName(QString::fromUtf8("darkMinionH3"));
        darkMinionH3->setGeometry(QRect(1000, 250, 40, 20));
        darkMinionH3->setAlignment(Qt::AlignCenter);
        darkMinionA0 = new QLabel(HearthstoneClass);
        darkMinionA0->setObjectName(QString::fromUtf8("darkMinionA0"));
        darkMinionA0->setGeometry(QRect(600, 250, 40, 20));
        darkMinionA0->setAlignment(Qt::AlignCenter);
        darkMinionH2 = new QLabel(HearthstoneClass);
        darkMinionH2->setObjectName(QString::fromUtf8("darkMinionH2"));
        darkMinionH2->setGeometry(QRect(880, 250, 40, 20));
        darkMinionH2->setAlignment(Qt::AlignCenter);
        darkMinionA4 = new QLabel(HearthstoneClass);
        darkMinionA4->setObjectName(QString::fromUtf8("darkMinionA4"));
        darkMinionA4->setGeometry(QRect(1080, 250, 40, 20));
        darkMinionA4->setAlignment(Qt::AlignCenter);
        darkMinionH0 = new QLabel(HearthstoneClass);
        darkMinionH0->setObjectName(QString::fromUtf8("darkMinionH0"));
        darkMinionH0->setGeometry(QRect(640, 250, 40, 20));
        darkMinionH0->setAlignment(Qt::AlignCenter);
        darkMinionA5 = new QLabel(HearthstoneClass);
        darkMinionA5->setObjectName(QString::fromUtf8("darkMinionA5"));
        darkMinionA5->setGeometry(QRect(1200, 250, 40, 20));
        darkMinionA5->setAlignment(Qt::AlignCenter);
        darkMinionH4 = new QLabel(HearthstoneClass);
        darkMinionH4->setObjectName(QString::fromUtf8("darkMinionH4"));
        darkMinionH4->setGeometry(QRect(1120, 250, 40, 20));
        darkMinionH4->setAlignment(Qt::AlignCenter);
        darkMinionA1 = new QLabel(HearthstoneClass);
        darkMinionA1->setObjectName(QString::fromUtf8("darkMinionA1"));
        darkMinionA1->setGeometry(QRect(720, 250, 40, 20));
        darkMinionA1->setAlignment(Qt::AlignCenter);
        darkMinionH1 = new QLabel(HearthstoneClass);
        darkMinionH1->setObjectName(QString::fromUtf8("darkMinionH1"));
        darkMinionH1->setGeometry(QRect(760, 250, 40, 20));
        darkMinionH1->setAlignment(Qt::AlignCenter);
        darkMinionA2 = new QLabel(HearthstoneClass);
        darkMinionA2->setObjectName(QString::fromUtf8("darkMinionA2"));
        darkMinionA2->setGeometry(QRect(840, 250, 40, 20));
        darkMinionA2->setAlignment(Qt::AlignCenter);
        darkMinionA3 = new QLabel(HearthstoneClass);
        darkMinionA3->setObjectName(QString::fromUtf8("darkMinionA3"));
        darkMinionA3->setGeometry(QRect(960, 250, 40, 20));
        darkMinionA3->setAlignment(Qt::AlignCenter);
        darkMinionH6 = new QLabel(HearthstoneClass);
        darkMinionH6->setObjectName(QString::fromUtf8("darkMinionH6"));
        darkMinionH6->setGeometry(QRect(1360, 250, 40, 20));
        darkMinionH6->setAlignment(Qt::AlignCenter);
        darkMinionH5 = new QLabel(HearthstoneClass);
        darkMinionH5->setObjectName(QString::fromUtf8("darkMinionH5"));
        darkMinionH5->setGeometry(QRect(1240, 250, 40, 20));
        darkMinionH5->setAlignment(Qt::AlignCenter);
        darkMinionA6 = new QLabel(HearthstoneClass);
        darkMinionA6->setObjectName(QString::fromUtf8("darkMinionA6"));
        darkMinionA6->setGeometry(QRect(1320, 250, 40, 20));
        darkMinionA6->setAlignment(Qt::AlignCenter);
        darkMinionI6 = new QLabel(HearthstoneClass);
        darkMinionI6->setObjectName(QString::fromUtf8("darkMinionI6"));
        darkMinionI6->setGeometry(QRect(1320, 210, 80, 40));
        darkMinionI6->setAlignment(Qt::AlignCenter);
        darkMinionI1 = new QLabel(HearthstoneClass);
        darkMinionI1->setObjectName(QString::fromUtf8("darkMinionI1"));
        darkMinionI1->setGeometry(QRect(720, 210, 80, 40));
        darkMinionI1->setAlignment(Qt::AlignCenter);
        darkMinionI5 = new QLabel(HearthstoneClass);
        darkMinionI5->setObjectName(QString::fromUtf8("darkMinionI5"));
        darkMinionI5->setGeometry(QRect(1200, 210, 80, 40));
        darkMinionI5->setAlignment(Qt::AlignCenter);
        darkMinionI3 = new QLabel(HearthstoneClass);
        darkMinionI3->setObjectName(QString::fromUtf8("darkMinionI3"));
        darkMinionI3->setGeometry(QRect(960, 210, 80, 40));
        darkMinionI3->setAlignment(Qt::AlignCenter);
        darkMinionI2 = new QLabel(HearthstoneClass);
        darkMinionI2->setObjectName(QString::fromUtf8("darkMinionI2"));
        darkMinionI2->setGeometry(QRect(840, 210, 80, 40));
        darkMinionI2->setAlignment(Qt::AlignCenter);
        darkMinionI0 = new QLabel(HearthstoneClass);
        darkMinionI0->setObjectName(QString::fromUtf8("darkMinionI0"));
        darkMinionI0->setGeometry(QRect(600, 210, 80, 40));
        darkMinionI0->setAlignment(Qt::AlignCenter);
        darkMinionI4 = new QLabel(HearthstoneClass);
        darkMinionI4->setObjectName(QString::fromUtf8("darkMinionI4"));
        darkMinionI4->setGeometry(QRect(1080, 210, 80, 40));
        darkMinionI4->setAlignment(Qt::AlignCenter);
        lightMinionI0 = new QLabel(HearthstoneClass);
        lightMinionI0->setObjectName(QString::fromUtf8("lightMinionI0"));
        lightMinionI0->setGeometry(QRect(600, 490, 80, 40));
        lightMinionI0->setAlignment(Qt::AlignCenter);
        lightMinionI1 = new QLabel(HearthstoneClass);
        lightMinionI1->setObjectName(QString::fromUtf8("lightMinionI1"));
        lightMinionI1->setGeometry(QRect(720, 490, 80, 40));
        lightMinionI1->setAlignment(Qt::AlignCenter);
        lightMinionI5 = new QLabel(HearthstoneClass);
        lightMinionI5->setObjectName(QString::fromUtf8("lightMinionI5"));
        lightMinionI5->setGeometry(QRect(1200, 490, 80, 40));
        lightMinionI5->setAlignment(Qt::AlignCenter);
        lightMinionI6 = new QLabel(HearthstoneClass);
        lightMinionI6->setObjectName(QString::fromUtf8("lightMinionI6"));
        lightMinionI6->setGeometry(QRect(1320, 490, 80, 40));
        lightMinionI6->setAlignment(Qt::AlignCenter);
        lightMinionI2 = new QLabel(HearthstoneClass);
        lightMinionI2->setObjectName(QString::fromUtf8("lightMinionI2"));
        lightMinionI2->setGeometry(QRect(840, 490, 80, 40));
        lightMinionI2->setAlignment(Qt::AlignCenter);
        lightMinionI3 = new QLabel(HearthstoneClass);
        lightMinionI3->setObjectName(QString::fromUtf8("lightMinionI3"));
        lightMinionI3->setGeometry(QRect(960, 490, 80, 40));
        lightMinionI3->setAlignment(Qt::AlignCenter);
        lightMinionI4 = new QLabel(HearthstoneClass);
        lightMinionI4->setObjectName(QString::fromUtf8("lightMinionI4"));
        lightMinionI4->setGeometry(QRect(1080, 490, 80, 40));
        lightMinionI4->setAlignment(Qt::AlignCenter);
        lightHeroA = new QLabel(HearthstoneClass);
        lightHeroA->setObjectName(QString::fromUtf8("lightHeroA"));
        lightHeroA->setGeometry(QRect(960, 630, 40, 20));
        lightHeroA->setAlignment(Qt::AlignCenter);
        lightHeroH = new QLabel(HearthstoneClass);
        lightHeroH->setObjectName(QString::fromUtf8("lightHeroH"));
        lightHeroH->setGeometry(QRect(995, 630, 50, 20));
        lightHeroH->setAlignment(Qt::AlignCenter);
        darkHeroA = new QLabel(HearthstoneClass);
        darkHeroA->setObjectName(QString::fromUtf8("darkHeroA"));
        darkHeroA->setGeometry(QRect(960, 90, 40, 20));
        darkHeroA->setAlignment(Qt::AlignCenter);
        darkHeroH = new QLabel(HearthstoneClass);
        darkHeroH->setObjectName(QString::fromUtf8("darkHeroH"));
        darkHeroH->setGeometry(QRect(995, 90, 50, 20));
        darkHeroH->setAlignment(Qt::AlignCenter);
        lightWeaponA = new QLabel(HearthstoneClass);
        lightWeaponA->setObjectName(QString::fromUtf8("lightWeaponA"));
        lightWeaponA->setGeometry(QRect(870, 630, 40, 20));
        lightWeaponA->setAlignment(Qt::AlignCenter);
        lightWeaponH = new QLabel(HearthstoneClass);
        lightWeaponH->setObjectName(QString::fromUtf8("lightWeaponH"));
        lightWeaponH->setGeometry(QRect(910, 630, 40, 20));
        lightWeaponH->setAlignment(Qt::AlignCenter);
        darkWeaponA = new QLabel(HearthstoneClass);
        darkWeaponA->setObjectName(QString::fromUtf8("darkWeaponA"));
        darkWeaponA->setGeometry(QRect(870, 90, 40, 20));
        darkWeaponA->setAlignment(Qt::AlignCenter);
        darkWeaponH = new QLabel(HearthstoneClass);
        darkWeaponH->setObjectName(QString::fromUtf8("darkWeaponH"));
        darkWeaponH->setGeometry(QRect(910, 90, 40, 20));
        darkWeaponH->setAlignment(Qt::AlignCenter);
        darkSubFrame = new QLabel(HearthstoneClass);
        darkSubFrame->setObjectName(QString::fromUtf8("darkSubFrame"));
        darkSubFrame->setGeometry(QRect(275, 80, 240, 160));
        darkSubFrame->setFrameShape(QFrame::Box);
        darkSubFrame->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        lightSubFrame = new QLabel(HearthstoneClass);
        lightSubFrame->setObjectName(QString::fromUtf8("lightSubFrame"));
        lightSubFrame->setGeometry(QRect(275, 261, 240, 160));
        lightSubFrame->setFrameShape(QFrame::Box);
        lightSubFrame->setAlignment(Qt::AlignHCenter|Qt::AlignTop);
        darkChoice0 = new QPushButton(HearthstoneClass);
        darkChoice0->setObjectName(QString::fromUtf8("darkChoice0"));
        darkChoice0->setGeometry(QRect(285, 130, 220, 30));
        darkChoice1 = new QPushButton(HearthstoneClass);
        darkChoice1->setObjectName(QString::fromUtf8("darkChoice1"));
        darkChoice1->setGeometry(QRect(285, 180, 220, 30));
        lightChoice1 = new QPushButton(HearthstoneClass);
        lightChoice1->setObjectName(QString::fromUtf8("lightChoice1"));
        lightChoice1->setGeometry(QRect(285, 361, 220, 30));
        lightChoice0 = new QPushButton(HearthstoneClass);
        lightChoice0->setObjectName(QString::fromUtf8("lightChoice0"));
        lightChoice0->setGeometry(QRect(285, 311, 220, 30));
        prompt2 = new QLabel(HearthstoneClass);
        prompt2->setObjectName(QString::fromUtf8("prompt2"));
        prompt2->setGeometry(QRect(950, 10, 500, 60));
        prompt2->setFont(font);
        prompt2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        quit = new QPushButton(HearthstoneClass);
        quit->setObjectName(QString::fromUtf8("quit"));
        quit->setGeometry(QRect(700, 800, 100, 30));
        quitMessage = new QLabel(HearthstoneClass);
        quitMessage->setObjectName(QString::fromUtf8("quitMessage"));
        quitMessage->setGeometry(QRect(500, 300, 500, 60));
        QFont font3;
        font3.setPointSize(30);
        quitMessage->setFont(font3);
        quitMessage->setAlignment(Qt::AlignCenter);
        mana0 = new QLabel(HearthstoneClass);
        mana0->setObjectName(QString::fromUtf8("mana0"));
        mana0->setGeometry(QRect(455, 690, 25, 25));
        mana1 = new QLabel(HearthstoneClass);
        mana1->setObjectName(QString::fromUtf8("mana1"));
        mana1->setGeometry(QRect(495, 690, 25, 25));
        mana2 = new QLabel(HearthstoneClass);
        mana2->setObjectName(QString::fromUtf8("mana2"));
        mana2->setGeometry(QRect(535, 690, 25, 25));
        mana3 = new QLabel(HearthstoneClass);
        mana3->setObjectName(QString::fromUtf8("mana3"));
        mana3->setGeometry(QRect(575, 690, 25, 25));
        mana4 = new QLabel(HearthstoneClass);
        mana4->setObjectName(QString::fromUtf8("mana4"));
        mana4->setGeometry(QRect(615, 690, 25, 25));
        mana5 = new QLabel(HearthstoneClass);
        mana5->setObjectName(QString::fromUtf8("mana5"));
        mana5->setGeometry(QRect(655, 690, 25, 25));
        mana6 = new QLabel(HearthstoneClass);
        mana6->setObjectName(QString::fromUtf8("mana6"));
        mana6->setGeometry(QRect(695, 690, 25, 25));
        mana7 = new QLabel(HearthstoneClass);
        mana7->setObjectName(QString::fromUtf8("mana7"));
        mana7->setGeometry(QRect(735, 690, 25, 25));
        mana8 = new QLabel(HearthstoneClass);
        mana8->setObjectName(QString::fromUtf8("mana8"));
        mana8->setGeometry(QRect(775, 690, 25, 25));
        mana9 = new QLabel(HearthstoneClass);
        mana9->setObjectName(QString::fromUtf8("mana9"));
        mana9->setGeometry(QRect(815, 690, 25, 25));
        cancel = new QPushButton(HearthstoneClass);
        cancel->setObjectName(QString::fromUtf8("cancel"));
        cancel->setGeometry(QRect(1375, 790, 100, 30));
        lightWeapon = new QLabel(HearthstoneClass);
        lightWeapon->setObjectName(QString::fromUtf8("lightWeapon"));
        lightWeapon->setGeometry(QRect(870, 550, 80, 80));
        lightWeapon->setFrameShape(QFrame::Box);
        darkWeapon = new QLabel(HearthstoneClass);
        darkWeapon->setObjectName(QString::fromUtf8("darkWeapon"));
        darkWeapon->setGeometry(QRect(870, 110, 80, 80));
        darkWeapon->setFrameShape(QFrame::Box);
        darkHero = new QPushButton(HearthstoneClass);
        darkHero->setObjectName(QString::fromUtf8("darkHero"));
        darkHero->setGeometry(QRect(960, 110, 80, 80));
        lightHero = new QPushButton(HearthstoneClass);
        lightHero->setObjectName(QString::fromUtf8("lightHero"));
        lightHero->setGeometry(QRect(960, 550, 80, 80));
        darkHeroI = new QLabel(HearthstoneClass);
        darkHeroI->setObjectName(QString::fromUtf8("darkHeroI"));
        darkHeroI->setGeometry(QRect(960, 70, 80, 20));
        darkHeroI->setAlignment(Qt::AlignCenter);
        lightHeroI = new QLabel(HearthstoneClass);
        lightHeroI->setObjectName(QString::fromUtf8("lightHeroI"));
        lightHeroI->setGeometry(QRect(960, 650, 80, 20));
        lightHeroI->setAlignment(Qt::AlignCenter);
        chooseBtn0r = new QPushButton(HearthstoneClass);
        chooseBtn0r->setObjectName(QString::fromUtf8("chooseBtn0r"));
        chooseBtn0r->setGeometry(QRect(108, 90, 240, 341));
        chooseBtn0r->setMinimumSize(QSize(240, 341));
        chooseBtn0r->setMaximumSize(QSize(240, 341));
        QIcon icon;
        icon.addFile(QString::fromUtf8("replace.png"), QSize(), QIcon::Normal, QIcon::Off);
        chooseBtn0r->setIcon(icon);
        chooseBtn0r->setIconSize(QSize(160, 160));
        chooseBtn4r = new QPushButton(HearthstoneClass);
        chooseBtn4r->setObjectName(QString::fromUtf8("chooseBtn4r"));
        chooseBtn4r->setGeometry(QRect(452, 540, 240, 341));
        chooseBtn4r->setMinimumSize(QSize(240, 341));
        chooseBtn4r->setMaximumSize(QSize(240, 341));
        chooseBtn4r->setIcon(icon);
        chooseBtn4r->setIconSize(QSize(160, 160));
        chooseBtn3r = new QPushButton(HearthstoneClass);
        chooseBtn3r->setObjectName(QString::fromUtf8("chooseBtn3r"));
        chooseBtn3r->setGeometry(QRect(108, 540, 240, 341));
        chooseBtn3r->setMinimumSize(QSize(240, 341));
        chooseBtn3r->setMaximumSize(QSize(240, 341));
        chooseBtn3r->setIcon(icon);
        chooseBtn3r->setIconSize(QSize(160, 160));
        chooseBtn1r = new QPushButton(HearthstoneClass);
        chooseBtn1r->setObjectName(QString::fromUtf8("chooseBtn1r"));
        chooseBtn1r->setGeometry(QRect(452, 90, 240, 341));
        chooseBtn1r->setMinimumSize(QSize(240, 341));
        chooseBtn1r->setMaximumSize(QSize(240, 341));
        chooseBtn1r->setIcon(icon);
        chooseBtn1r->setIconSize(QSize(160, 160));
        chooseBtn5r = new QPushButton(HearthstoneClass);
        chooseBtn5r->setObjectName(QString::fromUtf8("chooseBtn5r"));
        chooseBtn5r->setGeometry(QRect(800, 540, 240, 341));
        chooseBtn5r->setMinimumSize(QSize(240, 341));
        chooseBtn5r->setMaximumSize(QSize(240, 341));
        chooseBtn5r->setIcon(icon);
        chooseBtn5r->setIconSize(QSize(160, 160));
        chooseBtn6r = new QPushButton(HearthstoneClass);
        chooseBtn6r->setObjectName(QString::fromUtf8("chooseBtn6r"));
        chooseBtn6r->setGeometry(QRect(1148, 540, 240, 341));
        chooseBtn6r->setMinimumSize(QSize(240, 341));
        chooseBtn6r->setMaximumSize(QSize(240, 341));
        chooseBtn6r->setIcon(icon);
        chooseBtn6r->setIconSize(QSize(160, 160));
        chooseBtn2r = new QPushButton(HearthstoneClass);
        chooseBtn2r->setObjectName(QString::fromUtf8("chooseBtn2r"));
        chooseBtn2r->setGeometry(QRect(800, 90, 240, 341));
        chooseBtn2r->setMinimumSize(QSize(240, 341));
        chooseBtn2r->setMaximumSize(QSize(240, 341));
        chooseBtn2r->setIcon(icon);
        chooseBtn2r->setIconSize(QSize(160, 160));
        cardMana = new QLabel(HearthstoneClass);
        cardMana->setObjectName(QString::fromUtf8("cardMana"));
        cardMana->setGeometry(QRect(27, 98, 49, 51));
        QFont font4;
        font4.setPointSize(20);
        font4.setBold(true);
        cardMana->setFont(font4);
        cardMana->setAutoFillBackground(true);
        cardMana->setAlignment(Qt::AlignCenter);
        cardAttack = new QLabel(HearthstoneClass);
        cardAttack->setObjectName(QString::fromUtf8("cardAttack"));
        cardAttack->setGeometry(QRect(30, 366, 49, 41));
        cardAttack->setFont(font4);
        cardAttack->setAutoFillBackground(true);
        cardAttack->setAlignment(Qt::AlignCenter);
        cardHealth = new QLabel(HearthstoneClass);
        cardHealth->setObjectName(QString::fromUtf8("cardHealth"));
        cardHealth->setGeometry(QRect(204, 366, 49, 41));
        cardHealth->setFont(font4);
        cardHealth->setAutoFillBackground(true);
        cardHealth->setAlignment(Qt::AlignCenter);
        cardSkill = new QLabel(HearthstoneClass);
        cardSkill->setObjectName(QString::fromUtf8("cardSkill"));
        cardSkill->setGeometry(QRect(112, 90, 49, 51));
        cardSkill->setFont(font4);
        cardSkill->setAutoFillBackground(true);
        cardSkill->setAlignment(Qt::AlignCenter);
        place = new QPushButton(HearthstoneClass);
        place->setObjectName(QString::fromUtf8("place"));
        place->setGeometry(QRect(1375, 740, 100, 30));
        lightWeaponI = new QLabel(HearthstoneClass);
        lightWeaponI->setObjectName(QString::fromUtf8("lightWeaponI"));
        lightWeaponI->setGeometry(QRect(870, 650, 80, 20));
        lightWeaponI->setAlignment(Qt::AlignCenter);
        darkWeaponI = new QLabel(HearthstoneClass);
        darkWeaponI->setObjectName(QString::fromUtf8("darkWeaponI"));
        darkWeaponI->setGeometry(QRect(870, 70, 80, 20));
        darkWeaponI->setAlignment(Qt::AlignCenter);
        chooseBtn2r->raise();
        chooseBtn5r->raise();
        history->raise();
        logo->raise();
        chooseBtn1->raise();
        chooseBtn2->raise();
        chooseBtn0->raise();
        chooseBtn5->raise();
        chooseBtn3->raise();
        chooseBtn6->raise();
        chooseBtn4->raise();
        quit->raise();
        quitMessage->raise();
        cardBtn2->raise();
        cardBtn0->raise();
        cardBtn1->raise();
        cardBtn5->raise();
        cardBtn3->raise();
        cardBtn4->raise();
        cardBtn6->raise();
        cardBtn7->raise();
        cardBtn8->raise();
        cardBtn9->raise();
        done->raise();
        chooseInfo1->raise();
        chooseInfo0->raise();
        prompt0->raise();
        gameInfo1->raise();
        gameInfo3->raise();
        gameInfo0->raise();
        gameInfo2->raise();
        prompt1->raise();
        start->raise();
        finish->raise();
        darkMinion0->raise();
        darkMinion1->raise();
        darkMinion2->raise();
        darkMinion3->raise();
        darkMinion4->raise();
        darkMinion5->raise();
        darkMinion6->raise();
        lightMinion0->raise();
        lightMinion1->raise();
        lightMinion2->raise();
        lightMinion3->raise();
        lightMinion4->raise();
        lightMinion5->raise();
        lightMinion6->raise();
        lightPlace0->raise();
        lightPlace1->raise();
        lightPlace2->raise();
        lightPlace3->raise();
        lightPlace4->raise();
        lightPlace5->raise();
        lightPlace6->raise();
        lightPlace7->raise();
        darkPlace1->raise();
        darkPlace7->raise();
        darkPlace2->raise();
        darkPlace4->raise();
        darkPlace5->raise();
        darkPlace3->raise();
        darkPlace0->raise();
        darkPlace6->raise();
        lightSkill->raise();
        darkSkill->raise();
        lightMinionA0->raise();
        lightMinionA1->raise();
        lightMinionA2->raise();
        lightMinionA3->raise();
        lightMinionA4->raise();
        lightMinionA5->raise();
        lightMinionA6->raise();
        lightMinionH0->raise();
        lightMinionH1->raise();
        lightMinionH4->raise();
        lightMinionH2->raise();
        lightMinionH3->raise();
        lightMinionH5->raise();
        lightMinionH6->raise();
        darkMinionH3->raise();
        darkMinionA0->raise();
        darkMinionH2->raise();
        darkMinionA4->raise();
        darkMinionH0->raise();
        darkMinionA5->raise();
        darkMinionH4->raise();
        darkMinionA1->raise();
        darkMinionH1->raise();
        darkMinionA2->raise();
        darkMinionA3->raise();
        darkMinionH6->raise();
        darkMinionH5->raise();
        darkMinionA6->raise();
        darkMinionI6->raise();
        darkMinionI1->raise();
        darkMinionI5->raise();
        darkMinionI3->raise();
        darkMinionI2->raise();
        darkMinionI0->raise();
        darkMinionI4->raise();
        lightMinionI0->raise();
        lightMinionI1->raise();
        lightMinionI5->raise();
        lightMinionI6->raise();
        lightMinionI2->raise();
        lightMinionI3->raise();
        lightMinionI4->raise();
        lightHeroA->raise();
        lightHeroH->raise();
        darkHeroA->raise();
        darkHeroH->raise();
        lightWeaponA->raise();
        lightWeaponH->raise();
        darkWeaponA->raise();
        darkWeaponH->raise();
        darkSubFrame->raise();
        lightSubFrame->raise();
        darkChoice0->raise();
        darkChoice1->raise();
        lightChoice1->raise();
        lightChoice0->raise();
        prompt2->raise();
        mana0->raise();
        mana1->raise();
        mana2->raise();
        mana3->raise();
        mana4->raise();
        mana5->raise();
        mana6->raise();
        mana7->raise();
        mana8->raise();
        mana9->raise();
        cancel->raise();
        lightWeapon->raise();
        darkWeapon->raise();
        darkHero->raise();
        lightHero->raise();
        darkHeroI->raise();
        lightHeroI->raise();
        chooseBtn0r->raise();
        chooseBtn4r->raise();
        chooseBtn3r->raise();
        chooseBtn1r->raise();
        chooseBtn6r->raise();
        cardView->raise();
        cardMana->raise();
        cardAttack->raise();
        cardHealth->raise();
        cardSkill->raise();
        place->raise();
        lightWeaponI->raise();
        darkWeaponI->raise();

        retranslateUi(HearthstoneClass);

        QMetaObject::connectSlotsByName(HearthstoneClass);
    } // setupUi

    void retranslateUi(QWidget *HearthstoneClass)
    {
        HearthstoneClass->setWindowTitle(QCoreApplication::translate("HearthstoneClass", "Hearthstone", nullptr));
        logo->setText(QString());
        start->setText(QCoreApplication::translate("HearthstoneClass", "Start", nullptr));
        done->setText(QCoreApplication::translate("HearthstoneClass", "Done", nullptr));
        chooseInfo1->setText(QString());
        chooseInfo0->setText(QString());
        prompt0->setText(QCoreApplication::translate("HearthstoneClass", "Click a card to replace it with a new one", nullptr));
        gameInfo1->setText(QCoreApplication::translate("HearthstoneClass", "TEXT HERE", nullptr));
        gameInfo3->setText(QCoreApplication::translate("HearthstoneClass", "TEXT HERE", nullptr));
        gameInfo0->setText(QCoreApplication::translate("HearthstoneClass", "TEXT HERE", nullptr));
        gameInfo2->setText(QCoreApplication::translate("HearthstoneClass", "TEXT HERE", nullptr));
        finish->setText(QCoreApplication::translate("HearthstoneClass", "Finish", nullptr));
        prompt1->setText(QCoreApplication::translate("HearthstoneClass", "TEXT HERE", nullptr));
        cardView->setText(QCoreApplication::translate("HearthstoneClass", "<html><head/><body><p><span style=\" font-size:16pt;\">To view cards detail:</span></p><p><span style=\" font-size:16pt;\">Press Keys &quot;0&quot;~\342\200\2349\342\200\235</span></p><p><span style=\" font-size:16pt;\">To view skills, weapons </span></p><p><span style=\" font-size:16pt;\">and minions detail: </span></p><p><span style=\" font-size:16pt;\">Press Keys &quot;Q&quot;~\342\200\234O\342\200\235</span></p><p><span style=\" font-size:16pt;\">and &quot;A&quot;~&quot;L&quot;</span></p></body></html>", nullptr));
        history->setText(QString());
        chooseBtn5->setText(QString());
        chooseBtn6->setText(QString());
        chooseBtn3->setText(QString());
        chooseBtn1->setText(QString());
        chooseBtn2->setText(QString());
        chooseBtn4->setText(QString());
        chooseBtn0->setText(QString());
        cardBtn2->setText(QString());
        cardBtn0->setText(QString());
        cardBtn1->setText(QString());
        cardBtn5->setText(QString());
        cardBtn3->setText(QString());
        cardBtn4->setText(QString());
        cardBtn6->setText(QString());
        cardBtn7->setText(QString());
        cardBtn8->setText(QString());
        cardBtn9->setText(QString());
        darkMinion0->setText(QString());
        darkMinion1->setText(QString());
        darkMinion2->setText(QString());
        darkMinion3->setText(QString());
        darkMinion4->setText(QString());
        darkMinion5->setText(QString());
        darkMinion6->setText(QString());
        lightMinion0->setText(QString());
        lightMinion1->setText(QString());
        lightMinion2->setText(QString());
        lightMinion3->setText(QString());
        lightMinion4->setText(QString());
        lightMinion5->setText(QString());
        lightMinion6->setText(QString());
        lightPlace0->setText(QString());
        lightPlace1->setText(QString());
        lightPlace2->setText(QString());
        lightPlace3->setText(QString());
        lightPlace4->setText(QString());
        lightPlace5->setText(QString());
        lightPlace6->setText(QString());
        lightPlace7->setText(QString());
        darkPlace1->setText(QString());
        darkPlace7->setText(QString());
        darkPlace2->setText(QString());
        darkPlace4->setText(QString());
        darkPlace5->setText(QString());
        darkPlace3->setText(QString());
        darkPlace0->setText(QString());
        darkPlace6->setText(QString());
        lightSkill->setText(QString());
        darkSkill->setText(QString());
        lightMinionA0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionA6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionH6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionH5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionA6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkMinionI4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI0->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI1->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI5->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI6->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI3->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightMinionI4->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightHeroA->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightHeroH->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkHeroA->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkHeroH->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightWeaponA->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightWeaponH->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkWeaponA->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkWeaponH->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkSubFrame->setText(QCoreApplication::translate("HearthstoneClass", "Dark League's Subwindow", nullptr));
        lightSubFrame->setText(QCoreApplication::translate("HearthstoneClass", "Light League's Subwindow", nullptr));
        darkChoice0->setText(QCoreApplication::translate("HearthstoneClass", "Choice 1", nullptr));
        darkChoice1->setText(QCoreApplication::translate("HearthstoneClass", "Choice 2", nullptr));
        lightChoice1->setText(QCoreApplication::translate("HearthstoneClass", "Choice 2", nullptr));
        lightChoice0->setText(QCoreApplication::translate("HearthstoneClass", "Choice 1", nullptr));
        prompt2->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        quit->setText(QCoreApplication::translate("HearthstoneClass", "Quit", nullptr));
        quitMessage->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        mana0->setText(QString());
        mana1->setText(QString());
        mana2->setText(QString());
        mana3->setText(QString());
        mana4->setText(QString());
        mana5->setText(QString());
        mana6->setText(QString());
        mana7->setText(QString());
        mana8->setText(QString());
        mana9->setText(QString());
        cancel->setText(QCoreApplication::translate("HearthstoneClass", "Cancel", nullptr));
        lightWeapon->setText(QString());
        darkWeapon->setText(QString());
        darkHero->setText(QString());
        lightHero->setText(QString());
        darkHeroI->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        lightHeroI->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        chooseBtn0r->setText(QString());
        chooseBtn4r->setText(QString());
        chooseBtn3r->setText(QString());
        chooseBtn1r->setText(QString());
        chooseBtn5r->setText(QString());
        chooseBtn6r->setText(QString());
        chooseBtn2r->setText(QString());
        cardMana->setText(QCoreApplication::translate("HearthstoneClass", "20", nullptr));
        cardAttack->setText(QCoreApplication::translate("HearthstoneClass", "20", nullptr));
        cardHealth->setText(QCoreApplication::translate("HearthstoneClass", "3", nullptr));
        cardSkill->setText(QCoreApplication::translate("HearthstoneClass", "20", nullptr));
        place->setText(QCoreApplication::translate("HearthstoneClass", "Place", nullptr));
        lightWeaponI->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
        darkWeaponI->setText(QCoreApplication::translate("HearthstoneClass", "Text", nullptr));
    } // retranslateUi

};

namespace Ui {
    class HearthstoneClass: public Ui_HearthstoneClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_HEARTHSTONE_H
